source 'https://rubygems.org'

gem 'rails', '~> 8.0.3'

gem 'bootsnap', require: false
gem 'mysql2'
gem 'puma'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'sgcop', github: 'SonicGarden/sgcop', branch: 'main'
end
