source 'https://rubygems.org'

gem 'rails', '~> 8.0.3'

gem 'active_model_serializers'
gem 'bootsnap', require: false
gem 'devise'
gem 'devise_token_auth'
gem 'mysql2'
gem 'puma'
gem 'rack-cors'

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'bullet'
  gem 'sgcop', github: 'SonicGarden/sgcop', branch: 'main'
end

group :development do
  gem 'letter_opener_web'
end
